// client/components/DataManager.jsx
import Button from "./Button";
import { useRecoilValue } from "recoil";
import { selectedRoiState } from "./states";
const DataManger = () => {
  const selectedRois = useRecoilValue(selectedRoiState);

  function handleJson() {
    const beforeExport = {
      title: window.location.href,
      repo: "https://github.com/oxedom/parker",
      timeOfExport: Date.now(),
      rois: selectedRois,
    };

    // Convert the data object to JSON
    const jsonData = JSON.stringify(beforeExport);
    // Create a Blob with the JSON data
    const blob = new Blob([jsonData], { type: "application/json" });
    // Create a temporary URL for the Blob
    const url = URL.createObjectURL(blob);
    // Create a link element
    const link = document.createElement("a");
    link.href = url;
    link.download = "exported_data.json";
    // Simulate a click on the link element to trigger the file download
    link.click();
    // Clean up the temporary URL
    URL.revokeObjectURL(url);
  }
  function handleCsv() {}

  return (
    <>
      <div className="bg-black/60 backdrop-blur-sm pb-3 px-5  flex flex-col max-w-[500px]">
        <h2 className="  text-center text-3xl text-white pt-2 border-b border-orange-500 pb-1">
          {" "}
          Data manger{" "}
        </h2>
        <p className="text-white text-xl pt-4 ">
          {" "}
          Selection boxes keep track of events that occur, export that data
          locally to perform your own data exploration.
        </p>

        <div className="flex flex-col items-center mt-10 gap-y-2">
          <h1 className="text-white text-2xl "> Export as </h1>
          <div className="flex justify-center items-center gap-5 ">
            <Button onClick={handleJson}>
              {" "}
              <span className="text-lg"> JSON</span>{" "}
            </Button>
          </div>
        </div>
      </div>
    </>
  );
};

export default DataManger;

// client/src/components/DataManager.vue
<script setup lang="ts">
import { useRoisStore } from "@/stores/rois";
import AppButton from "@/components/AppButton.vue";

const rois = useRoisStore();

function handleExportJson() {
  const payload = {
    title: window.location.href,
    repo: "https://github.com/oxedom/parker",
    timeOfExport: Date.now(),
    rois: rois.items,
  };
  const blob = new Blob([JSON.stringify(payload)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "exported_data.json";
  link.click();
  URL.revokeObjectURL(url);
}
</script>

<template>
  <div
    class="bg-black/60 backdrop-blur-sm pb-3 px-5 flex flex-col max-w-[500px]"
  >
    <h2
      class="text-center text-3xl text-white pt-2 border-b border-orange-500 pb-1"
    >
      Data manager
    </h2>
    <p class="text-white text-xl pt-4">
      Selection boxes keep track of events that occur. Export that data locally
      to perform your own data exploration.
    </p>
    <div class="flex flex-col items-center mt-10 gap-y-2">
      <h1 class="text-white text-2xl">Export as</h1>
      <div class="flex justify-center items-center gap-5">
        <AppButton @click="handleExportJson">
          <span class="text-lg">JSON</span>
        </AppButton>
      </div>
    </div>
  </div>
</template>
