// client/components/LoadingScreen.jsx
import { useEffect, useRef, useState } from "react";
import { imageHeightState, imageWidthState } from "./states";
import { useRecoilValue } from "recoil";

const LoadingScreen = ({
  setWebRTCMode,
  setAllowWebcam,
  allowWebcam,
  WebRTCMode,
}) => {
  const imageWidth = useRecoilValue(imageWidthState);
  const imageHeight = useRecoilValue(imageHeightState);
  const enableWebcamRef = useRef(null);
  const [offsetX, setOffsetX] = useState(null);
  const [offsetY, setOffsetY] = useState(null);

  function updateBounding(canvasEl) {
    let canvasOffset = canvasEl.getBoundingClientRect();
    setOffsetX(canvasOffset.left);
    setOffsetY(canvasOffset.top);
  }

  useEffect(() => {
    updateBounding(enableWebcamRef.current);

    if (enableWebcamRef.current !== null) {
      let dotSring = "   ";
      let context = enableWebcamRef.current.getContext("2d");
      context.clearRect(0, 0, imageWidth, imageHeight);
      context.font = "bold 40px Arial";
      context.fillStyle = "blue";
      context.fillRect(0, 0, imageWidth, imageHeight);

      context.textAlign = "center";

      context.clearRect(0, 0, imageWidth, imageHeight);
      context.fillStyle = "black";

      if (allowWebcam) {
        context.fillRect(0, 0, imageWidth, imageHeight);
        context.fillStyle = "white";
        context.fillText(
          "    Attempting to detect webcam" + dotSring,
          imageWidth * 0.5,
          imageHeight * 0.4
        );
      } else if (WebRTCMode) {
        context.fillRect(0, 0, imageWidth, imageHeight);
        context.fillStyle = "white";

        const txt = `Invite with link \n to make a remote \n video connection`;
        const lines = txt.split("\n");
        const lineheight = 40;

        for (var i = 0; i < lines.length; i++)
          context.fillText(
            lines[i],
            imageWidth / 2,
            imageHeight / 2.5 + i * lineheight
          );
      } else {
        context.fillRect(0, 0, imageWidth, imageHeight);
        context.fillStyle = "white";
        const txt =
          "  Choose a video source from the \n navigation bar  \n  \n Demo/Webcam/Remote  ";
        const lines = txt.split("\n");
        const lineheight = 40;
        for (var i = 0; i < lines.length; i++)
          context.fillText(
            lines[i],
            imageWidth / 2,
            imageHeight / 2.5 + i * lineheight
          );
      }
    }
  }, [allowWebcam, WebRTCMode, imageHeight, imageWidth]);

  return (
    <>
      <canvas
        className="z-10 relative"
        ref={enableWebcamRef}
        height={imageHeight}
        width={imageWidth}
      ></canvas>
    </>
  );
};

export default LoadingScreen;

// client/src/components/LoadingScreen.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useDimensionsStore } from "@/stores/dimensions";

const props = defineProps<{
  allowWebcam: boolean;
  webRtcMode: boolean;
}>();

const dims = useDimensionsStore();
const canvasRef = ref<HTMLCanvasElement | null>(null);

const message = computed<string>(() => {
  if (props.allowWebcam) return "Attempting to detect webcam...";
  if (props.webRtcMode)
    return "Invite with link\nto make a remote\nvideo connection";
  return "Choose a video source from\nthe navigation bar\n\nDemo / Webcam / Remote";
});

function render() {
  const c = canvasRef.value;
  if (!c) return;
  const ctx = c.getContext("2d");
  if (!ctx) return;
  const w = dims.imageWidth;
  const h = dims.imageHeight;
  ctx.clearRect(0, 0, w, h);
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, w, h);
  ctx.fillStyle = "white";
  ctx.font = "bold 32px Arial";
  ctx.textAlign = "center";
  const lines = message.value.split("\n");
  const lh = 40;
  for (let i = 0; i < lines.length; i++) {
    ctx.fillText(lines[i], w / 2, h / 2.5 + i * lh);
  }
}

onMounted(render);
watch(
  () => [props.allowWebcam, props.webRtcMode, dims.imageWidth, dims.imageHeight],
  render,
);
</script>

<template>
  <canvas
    ref="canvasRef"
    class="z-10 relative"
    :width="dims.imageWidth"
    :height="dims.imageHeight"
  />
</template>
