// client/components/Navbar.jsx
import Link from "next/link";
import Navlink from "./Navlink.jsx";
import Router from "next/router";

const Navbar = () => {
  const handleVision = () => {
    if (Router.route == "/vision") {
      window.location.reload();
    }
  };
  return (
    <div className="hidden lg:block w-full text-center box-border w-max-[1028px] ">
      <nav className="z-[100]  h-[100px] absolute   ">
        <div className="flex gap-2 justify-center items-center">
          <Link href={"/"}>
            <h1 className=" text-bold text-3xl     justify-center items-center text-center  font-bold  text-white    hover:cursor-pointer">
              <p className=" p-2 ml-5 uppercase flex justify-items-center items-center gap-5 ">
                {" "}
                Parker
              </p>
            </h1>
          </Link>

          <div className="flex justify-self-center  items-center px-5 gap-10 ">
            <div
              onClick={handleVision}
              className="border-2  px-3 hover:scale-105 duration-200 rounded border-orange-600"
            >
              <Navlink url={"/vision"} text={"Try now"} />
            </div>

            <Navlink
              className="  

"
              url={"/about"}
              text={"About"}
            />

            <Navlink
              className="  

"
              url={"/docs"}
              text={"Docs"}
            />
          </div>
        </div>
      </nav>
    </div>
  );
};

export default Navbar;

// client/src/components/NavBar.vue
<script setup lang="ts">
import { useRoute, useRouter, RouterLink } from "vue-router";

const route = useRoute();
const router = useRouter();

function goVision() {
  if (route.path === "/vision") {
    window.location.reload();
  } else {
    router.push("/vision");
  }
}

function navlinkClass(target: string) {
  return route.path === target
    ? "text-white"
    : "text-gray-200 hover:text-white";
}
</script>

<template>
  <div
    class="my-5 sm:my-0 block w-full text-center max-w-[1028px] h-[50px] sm:h-16"
  >
    <nav class="z-[100] absolute">
      <div class="flex gap-2 justify-center items-center">
        <RouterLink to="/">
          <h1
            class="text-bold text-3xl text-center font-bold text-white hover:cursor-pointer"
          >
            <p
              class="p-2 ml-5 uppercase flex justify-items-center items-center gap-5"
            >
              Parker
            </p>
          </h1>
        </RouterLink>

        <div class="flex justify-self-center items-center px-5 gap-5">
          <div
            class="border-2 hidden sm:block px-2 hover:scale-105 duration-200 rounded border-orange-600 cursor-pointer"
            @click="goVision"
          >
            <span
              class="text-2xl font-bold"
              :class="navlinkClass('/vision')"
            >
              Try now
            </span>
          </div>
          <RouterLink to="/about" class="text-2xl font-bold" :class="navlinkClass('/about')">
            About
          </RouterLink>
        </div>
      </div>
    </nav>
  </div>
</template>
